/*
 *
 * AuthHoc constants
 *
 */

export const DEFAULT_ACTION = 'app/AuthHoc/DEFAULT_ACTION';

export const ACTIONS = {
  LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  GET_USER_TO_CALL: 'GET_USER_TO_CALL',
  ADD_TO_RECENT: 'ADD_TO_RECENT',
  ADD_TO_RECENT_API: 'ADD_TO_RECENT_API',

  REQUEST_CHANGE_CURRENT_USER_STATUS: 'REQUEST_CHANGE_CURRENT_USER_STATUS',
  CHANGE_CURRENT_USER_STATUS: 'CHANGE_CURRENT_USER_STATUS',

  FRIENDS_STATUS_CHANGED: 'FRIENDS_STATUS_CHANGED',

  CALL_USER: 'CALL_USER',
  END_CALL: 'END_CALL',

  LOGOUT: 'LOGOUT',

  RESTORE_STATE: 'RESTORE_STATE',

  UPLOAD_PICTURE_REQUEST: 'UPLOAD_PICTURE_REQUEST',
  UPLOAD_PICTURE_SUCCESS: 'UPLOAD_PICTURE_SUCCESS',
  UPLOAD_PICTURE_FAILED: 'UPLOAD_PICTURE_FAILED',

  FETCH_CONTACTS: 'FETCH_CONTACTS',
  FETCH_CONTACTS_SUCCESS: 'FETCH_CONTACTS_SUCCESS',

  FETCH_ROOMS: 'FETCH_ROOMS',
  FETCH_ROOMS_SUCCESS: 'FETCH_ROOMS_SUCCESS',
  FETCH_ROOMS_FAILED: 'FETCH_ROOMS_FAILED',

  ACCEPT_ROOM: 'ACCEPT_ROOM',
  ACCEPT_ROOM_SUCCESS: 'ACCEPT_ROOM_SUCCESS',

  REJECT_ROOM: 'REJECT_ROOM',
  REJECT_ROOM_SUCCESS: 'REJECT_ROOM_SUCCESS',
  
  CREATE_ROOM: 'CREATE_ROOM'
};
